name: ci

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - master
      - devel
      - strobopro_apps

  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

  pull_request_review:
    types:
      - submitted

  # Manual trigger.
  workflow_dispatch:

env:
  RELEASE: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node
        id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Deps
        run: |
          sudo apt-get install libasound2-dev
          npm install

      - name: Lint
        run: |
          npm run lint

      - name: Build
        run: |
          npm run build

      - name: Test
        run: |
          npm run test:ci
